name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test-template:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Copier
        run: pipx install copier

      - name: Render template
        run: copier copy --defaults --vcs-ref=HEAD . ./.devenv-test

      - name: Build devcontainer image
        run: docker build .devenv-test/.devcontainer
